[package]
name = "pico-detect"
version = "0.4.0"
authors = ["Rostyslav Bohomaz <rostyslav.db@gmail.com>"]
edition = "2018"
keywords = ["pico", "detection", "localization", "prediction"]
categories = ["computer-vision", "wasm"]
license = "MIT"
description = "Pixel Intensity Comparison-based Object (PICO) detection library."
repository = "https://github.com/rostyslavb/pico-detect"
readme = "README.md"
exclude = [
  "tests",
  "models",
  "examples",
  ".gitattributes"
]

[lib]
name = "pico_detect"
bench = false

[dependencies]
derive-new = "0.5"
nalgebra = "^0.21"
image = { version = "^0.23", default-features = false }
imageproc = { version = "^0.21", default-features = false }
rand = "^0.7"

[dev-dependencies]
image = "^0.23"
imageproc = "^0.21"
criterion = "0.3.3"
structopt = "0.3"
approx = "0.4.0"
rand_xorshift = "0.2.0"

[dev-dependencies.cargo-husky]
version = "1"
features = ["precommit-hook", "run-cargo-clippy"]

[[bench]]
name = "benchmarks"
harness = false

# uncomment for debugging
# [profile.release]
# debug = true
